version: '3.7'

x-environment-vars: &environment-vars
  DEBUG: "True"
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONIOENCODING: utf-8

services:
  tazalau:
    build: .
    volumes:
      - ./:/proj
    ports:
      - 8007:8000
    environment:
      <<: *environment-vars
    stdin_open: true
    tty: true
